baseURL = "https://ayamir.github.io/"
languageCode = "zh-CN"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
title = "Ayamir's Blog"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "LoveIt"
defaultTheme = "auto"

[params]
  # LoveIt 主题版本
version = "0.2.X"
description = "Welcome to Ayamir's blog."
keywords = ["GNU/Linux", "Algorithms", "Programming Language", "Software Engineer"]

[params.app]
  title = "Ayamir's blog"
  noFavicon = false

[params.search]
  enable = true
  type = "lunr"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 50
  highlightTag = "em"
  absoluteURL = false

[params.footer]
  enable = true
  custom = ''
  hugo = true
  copyright = true
  author = true
  since = 2021
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.section]
  paginate = 20
  rss = 10

[params.list]
  pagina = 20
  rss = 10

[params.home]
  rss = 10
  [params.home.profile]
  enable = true
  avatarURL = "https://avatars.githubusercontent.com/u/61657399?s=400&u=7a71222b05d3e29bae8c36647b078d8aad923bfe&v=4"
  social = true
  [params.home.posts]
  enable = true
  paginate = 6
  defaultHiddenFromHomePage = false

[params.social]
  GitHub = "ayamir"
  Zhihu = "MiraculousMoon"
  Email = "miracle_l@bupt.edu.cn"

# LoveIt 新增 | 0.2.5 TypeIt 配置
[params.typeit]
  # 每一步的打字速度 (单位是毫秒)
  speed = 100
  # 光标的闪烁速度 (单位是毫秒)
  cursorSpeed = 1000
  # 光标的字符 (支持 HTML 格式)
  cursorChar = "|"
  # 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
  duration = -1

# 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
[params.verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""

# LoveIt 新增 | 0.2.10 网站 SEO 配置
[params.seo]
  # 图片 URL
  image = ""
  # 缩略图 URL
  thumbnailUrl = ""

# LoveIt 新增 | 0.2.0 网站分析配置
[params.analytics]
  enable = false
  # Google Analytics
  [params.analytics.google]
    id = ""
    # 是否匿名化用户 IP
    anonymizeIP = true
  # Fathom Analytics
  [params.analytics.fathom]
    id = ""
    # 自行托管追踪器时的主机路径
    server = ""

# LoveIt 新增 | 0.2.7 Cookie 许可配置
[params.cookieconsent]
  enable = true
  # 用于 Cookie 许可横幅的文本字符串
  [params.cookieconsent.content]
    message = ""
    dismiss = ""
    link = ""

# LoveIt 更改 | 0.2.7 第三方库文件的 CDN 设置
[params.cdn]
  # CDN 数据文件名称, 默认不启用
  # ("jsdelivr.yml")
  # 位于 "themes/LoveIt/assets/data/cdn/" 目录
  # 可以在你的项目下相同路径存放你自己的数据文件:
  # "assets/data/cdn/"
  data = ""

# LoveIt 新增 | 0.2.8 兼容性设置
[params.compatibility]
  # 是否使用 Polyfill.io 来兼容旧式浏览器
  polyfill = false
  # 是否使用 object-fit-images 来兼容旧式浏览器
  objectFit = false

# 作者配置
[author]
  name = "Ayamir"
  email = "miracle_l@bupt.edu.cn"
  link = "https://github.com/ayamir"

# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# 隐私信息配置
[privacy]
  # LoveIt 删除 | 0.2.0 Google Analytics 相关隐私 (被 params.analytics.google 替代)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# 用于输出 Markdown 格式文档的设置
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# 用于 Hugo 输出文档的设置
[outputs]
  # LoveIt 更改 | 0.2.0
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
 [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
   noClasses = false
