baseURL = "https://ayamir.github.io"
languageCode = "zh-cn"
title = "Ayamir's blog"
theme = "github-style-pro"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "All is for liberty."
  github = "ayamir"
  email = "miracle_l@bupt.edu.cn"
  url = "https://github.com/ayamir"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "🎯"
  favicon = "/images/favicon.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  location = "China"
  enableUtterances = true

  [params.utterances]
    repo = "ayamir/ayamir.github.io"

  [[params.links]]
    title = "Zhihu"
    href = "https://www.zhihu.com/people/MiraculousMoon"
    icon = "/images/zhihu.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "UA-123456-789"
